# Generated by Django 4.2.4 on 2023-08-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
