# Generated by Django 4.2.4 on 2023-08-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
