# Generated by Django 4.2.4 on 2023-08-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
