# Generated by Django 4.2.4 on 2023-08-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_referral_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referrer',
            field=models.CharField(blank=True, default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
