# Generated by Django 4.2.4 on 2023-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referrer',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
