# Generated by Django 4.2.4 on 2023-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('P', 'Profit')], default='D', max_length=1)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('STATUS', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected')], default='P', max_length=1)),
                ('transacrion_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
