# Generated by Django 4.2.4 on 2023-08-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_status_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.asset'),
            preserve_default=False,
        ),
    ]
