# Generated by Django 4.2.4 on 2023-08-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Asset',
            new_name='asset',
        ),
    ]
