# Generated by Django 4.2.4 on 2023-08-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_transaction_user_alter_asset_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transacrion_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
