# Generated by Django 4.2.4 on 2023-08-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='min_refferral',
            new_name='min_referral',
        ),
    ]
