# Generated by Django 4.2.4 on 2023-08-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_rename_min_refferral_level_min_referral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
