# Generated by Django 4.2.4 on 2023-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='referral_profit_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
